repos:
  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
        types: [python]

  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black
        types: [python]

  - repo: https://gitlab.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        types: [python]

  - repo: https://github.com/commitizen-tools/commitizen
    rev: master
    hooks:
      - id: commitizen
        types: [python]
        stages: [commit-msg]

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        language: system
        entry: pytest
        pass_filenames: false
        always_run: true
        stages: [push]
